apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-status-backend-sa
  annotations:
    iam.gke.io/gcp-service-account: k8s-status-backend-sa@mslarkin-ext.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-status-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-status-backend
  template:
    metadata:
      labels:
        app: k8s-status-backend
    spec:
      serviceAccountName: k8s-status-backend-sa
      containers:
      - name: backend
        image: gcr.io/mslarkin-ext/k8s-status-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GOOGLE_CLOUD_PROJECT
          value: "mslarkin-ext"
        - name: PROJECT_IDS
          value: "mslarkin-ext,mslarkin-demo"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-status-backend
spec:
  selector:
    app: k8s-status-backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
