apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: model-ns
spec:
  serviceAccountName: model-ksa
  containers:
  - name: debug-container
    image: curlimages/curl
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
